#!/usr/bin/env python3
"""Compile generated wiki markdown from extracted entity JSON."""

from __future__ import annotations

import json
import re
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
ROOT = BASE.parent
ENTITY_JSON = BASE / "out" / "entities" / "entities.json"

WIKI_DIR = ROOT / "content" / "wiki"
TYPE_DIR = {
    "character": "characters",
    "artifact": "artifacts",
    "location": "locations",
    "faction": "factions",
}

# Phase 5 — preserve hand-maintained provenance blocks across regenerations.
_LORE_METADATA_RE = re.compile(
    r"(## Lore metadata\s*\n\n[\s\S]*?)(?=\n## |\Z)",
    re.MULTILINE,
)

# Markers written by the TS canon seeders (seed-canon-entities.ts,
# merge-character-dossier.ts). If any of these are present the file has been
# enriched beyond this script's template and regeneration would destroy data.
# Regression history: commit 631dc5b silently stripped 8 crew character
# dossiers because this script rewrote them from the thin template while those
# files still carried a <!-- generated:ingest --> sentinel above the seeded
# Canon Dossier block. The sentinel check is not sufficient on its own.
_ENRICHED_MARKERS = (
    "<!-- canon:dossier",
    "<!-- ai-dossier:",
    "## Canon Dossier",
    "## Dossier",
)


def is_enriched(existing: str) -> bool:
    return any(marker in existing for marker in _ENRICHED_MARKERS)


def preserve_lore_metadata(existing: str, new_md: str) -> str:
    """If the previous file had a Lore metadata section, splice it before ## Note."""
    m = _LORE_METADATA_RE.search(existing)
    if not m:
        return new_md
    lore_block = m.group(1).rstrip()
    if "## Note\n" in new_md:
        return new_md.replace("## Note\n", lore_block + "\n\n## Note\n", 1)
    return new_md + "\n\n" + lore_block


def write_if_generated(path: Path, content: str) -> None:
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if "<!-- generated:ingest -->" not in existing:
            return
        if is_enriched(existing):
            # Enriched files are owned by the TS canon seeders; regenerating
            # from this thin template would destroy the Canon Dossier /
            # ai-dossier blocks. Skip writing entirely.
            return
        content = preserve_lore_metadata(existing, content)
    path.write_text(content, encoding="utf-8")


def build_markdown(row: dict) -> str:
    refs = "\n".join(f"- Auto-detected appearance ({sid})." for sid in row["story_ids"])
    first_story = row["story_ids"][0] if row["story_ids"] else "CH01"
    return f"""# {row["name"]}
**Slug:** {row["slug"]}
Inventory entry (tiers: C)
reviewed: false

<!-- generated:ingest -->
<!-- ai-draft:start generated="{row.get("generated_at","")}" reviewed="false" -->
{row["summary"]}
<!-- ai-draft:end -->

## Appearances
{refs or f"- Auto-detected appearance ({first_story})."}

## Additional appearances
_(auto-generated; review and expand.)_

## Related
- [[{row["type"]}:{row["slug"]}]] appears-in [[story:{first_story.lower()}]]

## Note
Auto-generated by brain_lab/scripts/05_compile_wiki.py. Remove the generated marker to take manual ownership.
"""


def main() -> None:
    if not ENTITY_JSON.exists():
        raise SystemExit(f"Missing entities JSON: {ENTITY_JSON}")
    payload = json.loads(ENTITY_JSON.read_text(encoding="utf-8"))
    entities = payload.get("entities", [])
    count = 0
    expected_by_dir: dict[str, set[str]] = {subdir: set() for subdir in TYPE_DIR.values()}

    for row in entities:
        entity_type = row.get("type")
        subdir = TYPE_DIR.get(entity_type)
        if not subdir:
            continue
        out_dir = WIKI_DIR / subdir
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"{row['slug']}.md"
        expected_by_dir[subdir].add(out_path.name)
        md = build_markdown(row)
        write_if_generated(out_path, md)
        count += 1

    # Cleanup stale generated files no longer present in current entity set.
    for subdir, expected_names in expected_by_dir.items():
        dir_path = WIKI_DIR / subdir
        if not dir_path.exists():
            continue
        for path in dir_path.glob("*.md"):
            if path.name in expected_names:
                continue
            existing = path.read_text(encoding="utf-8")
            if "<!-- generated:ingest -->" not in existing:
                continue
            if is_enriched(existing):
                # Do not delete files the TS canon seeders own, even if the
                # current entity extraction did not surface them this run.
                continue
            path.unlink()

    print(f"Compiled {count} wiki files from {ENTITY_JSON}")


if __name__ == "__main__":
    main()
