// Auto-generated by scripts/generate-static-data.ts
// Do not edit manually. Run: npx tsx scripts/generate-static-data.ts

import type {
  CanonStatusV1,
  ContentTypeV1,
  SourceTypeV1,
  VisibilityPolicyV1,
} from "@/lib/wiki/taxonomy";

export type StorySource = "memoir" | "interview" | "family";
export type TimelineSource = "memoir" | "public_record" | "interview";

export interface StoryCard {
  storyId: string;
  slug: string;
  title: string;
  summary: string;
  source: StorySource;
  sourceDetail: string;
  lifeStage: string;
  themes: string[];
  wordCount: number;
  principles: string[];
  volume?: string;
  contentType: ContentTypeV1;
  sourceType: SourceTypeV1;
  canonStatus: CanonStatusV1;
  visibilityPolicy: VisibilityPolicyV1;
}

export interface ThemeCard {
  slug: string;
  name: string;
  storyCount: number;
  storyIds: string[];
}

export type PersonTier = "A" | "B" | "C" | "D";

export interface PersonCard {
  slug: string;
  name: string;
  tiers: PersonTier[];
  memoirStoryIds: string[];
  interviewStoryIds: string[];
  storyCount: number;
  note: string;
}

export interface TimelineEvent {
  year: number;
  event: string;
  organization: string;
  location: string;
  storyRef: string;
  illustration?: string;
  source: TimelineSource;
  sourceDetail?: string;
}

export const storiesData: StoryCard[] = [
  {
    "storyId": "CH01",
    "slug": "dustfall",
    "title": "Chapter 1: Dustfall",
    "summary": "The Martian wind didn’t howl-it whispered, dragging red dust in long, ribboned currents across the excavation field. Galen Voss stood at the edge of the south trench, boots buried ankle-deep in fine particulate. It clung to everything: mesh tarp, support struts, the knees of his suit. Even after weeks of excavation, it found new places to settle. Like memory. Like regret.",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Resonance"
    ],
    "wordCount": 2000,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH02",
    "slug": "footprints-in-silence",
    "title": "Chapter 2: Footprints in Silence",
    "summary": "Thane stood at the outer ring of the excavation grid, visor tinted against the Martian morning glare. The wind had dropped, but the dust still moved in low, lazy spirals-like breath beneath skin.",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Silence & Signal"
    ],
    "wordCount": 2647,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH03",
    "slug": "resonant-memory",
    "title": "Chapter 3: Resonant Memory",
    "summary": "The descent platform hummed beneath Lena’s boots, steady and deliberate, though she still felt the drop in her stomach. The shaft was shallow-only eight meters-but it pressed against her like a cathedral built too small. The air had changed. Still sterile. But heavier, somehow. Charged.",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Memory"
    ],
    "wordCount": 3029,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH04",
    "slug": "the-awakening-voice",
    "title": "Chapter 4: The Awakening Voice",
    "summary": "The command section of Valkyrie-1 was not a military bridge. It was a resonant core-a circular, partially domed space where purpose and presence converged. The architecture was smooth, quiet, and alive with meaning. Galen sat at the center-not to command, but to anchor.",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Activation"
    ],
    "wordCount": 3919,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH05",
    "slug": "echoes-of-intent",
    "title": "Chapter 5: Echoes of Intent",
    "summary": "The chamber wasn’t listed on any ship manifest.",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Intent"
    ],
    "wordCount": 4514,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH06",
    "slug": "alignment-vectors",
    "title": "Chapter 6: Alignment Vectors",
    "summary": "The corridor wasn’t listed on any ship manifest.",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Alignment"
    ],
    "wordCount": 4644,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH07",
    "slug": "harmonic-breach",
    "title": "Chapter 7: Harmonic Breach",
    "summary": "Caeden did not request assistance.",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Harmonics"
    ],
    "wordCount": 3591,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH08",
    "slug": "witness-protocol",
    "title": "Chapter 8: Witness Protocol",
    "summary": "+00:04:51 since Departure Vector Initiated",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Witness"
    ],
    "wordCount": 4722,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH09",
    "slug": "memory-carries-forward",
    "title": "Chapter 9: Memory Carries Forward",
    "summary": "+02:13:48 since Threshold Activation",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Legacy"
    ],
    "wordCount": 4224,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH10",
    "slug": "convergence-window",
    "title": "Chapter 10: Convergence Window",
    "summary": "+04:08:12 since Vault 002 Activation",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Convergence"
    ],
    "wordCount": 6265,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH11",
    "slug": "directive-14",
    "title": "Chapter 11: Directive 14",
    "summary": "+04:40:55 since Vault 002 Activation",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Threshold"
    ],
    "wordCount": 2704,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH12",
    "slug": "divergence",
    "title": "Chapter 12: Divergence",
    "summary": "Narrative chapter CH12.",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Covenant"
    ],
    "wordCount": 4334,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH13",
    "slug": "the-intercept",
    "title": "Chapter 13: The Intercept",
    "summary": "Narrative chapter CH13.",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Containment"
    ],
    "wordCount": 2261,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH14",
    "slug": "the-choice",
    "title": "Chapter 14: The Choice",
    "summary": "Narrative chapter CH14.",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Oracle"
    ],
    "wordCount": 2252,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH15",
    "slug": "the-signal-beneath",
    "title": "Chapter 15: The Signal Beneath",
    "summary": "Narrative chapter CH15.",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Sacrifice"
    ],
    "wordCount": 1455,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH16",
    "slug": "the-giza-pulse",
    "title": "Chapter 16: The Giza Pulse",
    "summary": "Narrative chapter CH16.",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Earth Echo"
    ],
    "wordCount": 2408,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  },
  {
    "storyId": "CH17",
    "slug": "vault-of-the-veil",
    "title": "Chapter 17: Vault of the Veil",
    "summary": "Narrative chapter CH17.",
    "source": "family",
    "sourceDetail": "",
    "lifeStage": "Main Narrative",
    "themes": [
      "Ascent"
    ],
    "wordCount": 2683,
    "principles": [],
    "volume": "P1",
    "contentType": "chapter",
    "sourceType": "book_i_chapter",
    "canonStatus": "canon",
    "visibilityPolicy": "progressive"
  }
];

export const themesData: ThemeCard[] = [];

export const peopleData: PersonCard[] = [
  {
    "slug": "alara",
    "name": "ALARA",
    "tiers": [],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  },
  {
    "slug": "amar-cael",
    "name": "Amar Cael",
    "tiers": [
      "C"
    ],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  },
  {
    "slug": "aven-voss",
    "name": "Aven Voss",
    "tiers": [
      "C"
    ],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  },
  {
    "slug": "caeden",
    "name": "CAEDEN",
    "tiers": [],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  },
  {
    "slug": "rhea-solari",
    "name": "Captain Rhea Solari",
    "tiers": [],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  },
  {
    "slug": "elara-varen",
    "name": "Elara Varen",
    "tiers": [
      "A"
    ],
    "memoirStoryIds": [
      "CH01"
    ],
    "interviewStoryIds": [],
    "storyCount": 1,
    "note": "Stub fiction character dropped in `content/wiki/characters/` so `/characters/elara-varen` renders without bespoke parser code."
  },
  {
    "slug": "elira-voss",
    "name": "Elira Voss",
    "tiers": [],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  },
  {
    "slug": "evelyn-tran",
    "name": "Evelyn Tran",
    "tiers": [
      "C"
    ],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  },
  {
    "slug": "galen-voss",
    "name": "Galen Voss",
    "tiers": [
      "C"
    ],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  },
  {
    "slug": "jax-reyes",
    "name": "Jax Reyes",
    "tiers": [
      "C"
    ],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  },
  {
    "slug": "jonah-revas",
    "name": "Jonah Revas",
    "tiers": [
      "C"
    ],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  },
  {
    "slug": "lena-osei",
    "name": "Lena Osei",
    "tiers": [
      "C"
    ],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  },
  {
    "slug": "marco-ruiz",
    "name": "Marco Ruiz",
    "tiers": [
      "C"
    ],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  },
  {
    "slug": "sovrin",
    "name": "SOVRIN",
    "tiers": [],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  },
  {
    "slug": "thane-meric",
    "name": "Thane Meric",
    "tiers": [
      "C"
    ],
    "memoirStoryIds": [],
    "interviewStoryIds": [],
    "storyCount": 0,
    "note": ""
  }
];

export const timelineData: TimelineEvent[] = [
  {
    "year": 2050,
    "event": "South trench excavation exposes Valkyrie-1",
    "organization": "",
    "location": "",
    "storyRef": "CH01",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Survey grid walks the buried hull’s silence",
    "organization": "",
    "location": "",
    "storyRef": "CH02",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Descent shaft: resonant strata under the trench",
    "organization": "",
    "location": "",
    "storyRef": "CH03",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Command core awakens to contact",
    "organization": "",
    "location": "",
    "storyRef": "CH04",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Manifest gaps: corridors not on any list",
    "organization": "",
    "location": "",
    "storyRef": "CH05",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Alignment geometry in unlisted passages",
    "organization": "",
    "location": "",
    "storyRef": "CH06",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Harmonic rupture stresses ship and crew",
    "organization": "",
    "location": "",
    "storyRef": "CH07",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Departure vector: witness protocol engages",
    "organization": "",
    "location": "",
    "storyRef": "CH08",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Threshold activation; memory persists",
    "organization": "",
    "location": "",
    "storyRef": "CH09",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Vault 002: convergence opens",
    "organization": "",
    "location": "",
    "storyRef": "CH10",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Directive 14 reframes authority",
    "organization": "",
    "location": "",
    "storyRef": "CH11",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Cascade choices across compartments",
    "organization": "",
    "location": "",
    "storyRef": "CH12",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Signal routing through the hull lattice",
    "organization": "",
    "location": "",
    "storyRef": "CH13",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Threshold debt comes due",
    "organization": "",
    "location": "",
    "storyRef": "CH14",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Edge cases at the convergence rim",
    "organization": "",
    "location": "",
    "storyRef": "CH15",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Earth-line pulse through the net",
    "organization": "",
    "location": "",
    "storyRef": "CH16",
    "source": "memoir"
  },
  {
    "year": 2050,
    "event": "Vault sequence advances; crew holds vector",
    "organization": "",
    "location": "",
    "storyRef": "CH17",
    "source": "memoir"
  }
];
